### ISSUE TITLE
How to change template?

### ISSUE THREAD

**Issue by Sensetivity** [rezaei121/yii2-jcrop#1]
Hello. How to change template? Any advice?

**Comment by rezaei121** [comment]
hi,
you must rewrite src/views/widget.php
also change assets.

**Comment by Sensetivity** [comment]
Okay, but it woldn`t working. Because if I chnage it in vendor folder I can`t push it.
And on live server I get default template.

**Comment by rezaei121** [comment]
I do this. save rewrite files in common/widget/jcrop.
for example see https://github.com/rezaei121/raspina/tree/master/common/widgets (rewrite alert widget)
