### ISSUE TITLE
Asset error

### ISSUE THREAD

**Issue by justscribe** [rezaei121/yii2-jcrop#3]
There is no '@vendor/bower/jcrop/' but '@vendor/bower-asset/jcrop/', file "JcropAsset.php"

namespace developit\jcrop;
use yii\web\AssetBundle;
class JcropAsset extends AssetBundle
{
    public $sourcePath = '@vendor/bower/jcrop/';
    public $js = [
        'js/jquery.Jcrop.min.js'
    ];
    public $css = [
        'css/jquery.Jcrop.min.css'
    ];
}

**Comment by justscribe** [comment]
Or  '@bower/jcrop/'

**Comment by rezaei121** [comment]
hi.
Try installing the asset-plugin (fxp-asset).

**Comment by krisanpaulino** [comment]
Just simply edit Asset files in ...vendor/developeit/yii2-jcrop/src. 

find 
`public $sourcePath = '@vendor/bower/.../';`

change it:

`public $sourcePath = '@bower/.../';`

**Comment by justscribe** [comment]
I have changed that, but I want to update sources through composer without any further changes.
